### ISSUE TITLE
Can the .publish cache directory be optional?

### ISSUE THREAD

**Issue by greypants** [shinnn/gulp-gh-pages#63]
I don't need the `.publish` folder to stick around, and it kinda gets in the way (I have to tell Sublime search and team members to ignore it). Any way to make this optional, or delete it on complete?

**Comment by shinnn** [comment]
[`cacheDir` option](https://github.com/shinnn/gulp-gh-pages/tree/65a0350b3fbbe0d8bef7b4c9d16e0e0923d9db24#optionscachedir) and [`os.tmpdir`](https://nodejs.org/api/os.html#os_os_tmpdir) help you.

**Comment by greypants** [comment]
Oh, nice. Didn't know about `os.tmpdir`. Thanks!

**Comment by DJTB** [comment]
On Ubuntu, this config actually created a folder named tmpPROJECTNAME at the root filetree rather than within the temp directory -> tmp/PROJECTNAME.

![screenshot from 2015-07-30 13 42 21](https://cloud.githubusercontent.com/assets/5353151/8975441/c08e773c-36c1-11e5-9f67-88e37ced1056.png)

Using path fixed this for me, and I think would work equally across win/mac/linux.
See [https://github.com/greypants/gulp-starter/pull/170](https://github.com/greypants/gulp-starter/pull/170) for a PR fix.

**Comment by shinnn** [comment]
http://www.catb.org/esr/faqs/smart-questions.html#forum
